package Extract_Transform_Load.multithread

object RsaBrokerLauncher {

  def main(args: Array[String]): Unit = {

    val spark = CreateSparkSessionUtilsNew.createSparkSession()

    spark.sql("set hive.exec.dynamic.partition=true")
    spark.sql("set hive.exec.dynamic.partition.mode=nonstrict")

    /*
    spark.sql(
      """
        |insert overwrite table hdb.ods_hdb_mysql_client_building_relation partition(mysql_dbname)
        |select
        |r_build_id,
        |id,
        |broker_id,
        |client_id,
        |building_id,
        |client_status,
        |client_status_old,
        |is_locked,
        |locked_at,
        |unlocked_at,
        |is_visited,
        |is_signed,
        |protect_time,
        |protect_time_old,
        |creater,
        |create_time,
        |create_time_old,
        |remark,
        |city_id,
        |is_remind,
        |mingyuan_status,
        |exhibition_room_id,
        |client_building_id,
        |visite_company,
        |visite_company_id,
        |visite_place,
        |visite_place_id,
        |rsa(client_name) as client_name_rsa,
        |md5(client_name) as client_name_md5,
        |is_id_card,
        |client_id_card,
        |activate_sign,
        |activate_sign_old,
        |bespeak_time,
        |source_id,
        |recommend_source,
        |platform,
        |health_intention,
        |employee_mark,
        |is_black,
        |org_id,
        |org_name,
        |user_type,
        |parent_user_type,
        |update_time,
        |update_time_old,
        |is_special,
        |owner_flag,
        |is_h5_delete,
        |rsa(client_phone) as client_phone_rsa,
        |md5(client_phone) as client_name_md5,
        |is_tuoke,
        |is_employee_et,
        |is_employee_et_old,
        |property_type,
        |is_make_up,
        |is_signing,
        |member_level,
        |member_level_old,
        |member_level_reward,
        |member_level_reward_old,
        |my_project_guid,
        |guid,
        |client_rb_id,
        |building_rb_id,
        |org_rb_Id,
        |visite_place_rb_id,
        |visite_company_rb_id,
        |sync_time,
        |recommend_ip,
        |source_rb_id,
        |province_name,
        |building_name,
        |company_id,
        |mysql_dbname
        |from hdb_test.ods_hdb_mysql_client_building_relation
        |""".stripMargin)

        spark.sql(
          """
            |insert overwrite table hdb.ods_hdb_mysql_client_building_visited partition(mysql_dbname)
            |select
            |r_build_id,
            |id,
            |client_id,
            |building_id,
            |status,
            |status_old,
            |signSeeHouse,
            |visited_time,
            |visited_time_old,
            |reception,
            |creater,
            |remark,
            |lifecycle_id,
            |recheck_user,
            |recheck_mark,
            |visit_review_status,
            |purpose,
            |purpose_old,
            |withSeeHouse,
            |my_visited_guid,
            |my_project_guid,
            |my_mobile_rsa,
            |my_mobile_md5,
            |is_exchange,
            |is_local_visit,
            |create_time,
            |create_time_old,
            |update_time,
            |is_lead,
            |saler_name_rsa,
            |saler_name_md5,
            |equipment_id,
            |broker_id,
            |client_rb_id,
            |lifecycle_rb_id,
            |guid,
            |building_rb_id,
            |sync_time,
            |building_name,
            |mysql_dbname
            |from hdb.ods_hdb_mysql_client_building_visited_old
            |""".stripMargin)

     */
    spark.sql(
      """
        |insert overwrite table hdb.ods_hdb_mysql_broker partition(mysql_dbname)
        |select
        |guid,
        |r_copy_id,
        |id,
        |rsa(m_phone),
        |md5(m_phone),
        |rsa(m_weixin),
        |md5(m_weixin),
        |rsa(m_qq),
        |md5(m_qq),
        |account_type,
        |superior_id,
        |broker_type,
        |city,
        |is_disabled,
        |ios_device,
        |android_device,
        |rsa(screen_name),
        |md5(screen_name),
        |rsa(password),
        |md5(password),
        |org_account,
        |create_time,
        |build_id,
        |dormant_status,
        |vocation,
        |active_time,
        |is_employee,
        |login_time,
        |source_from,
        |recommender_id,
        |province_id,
        |is_frozen,
        |frozen_start_time,
        |frozen_end_time,
        |register_from,
        |is_illegal,
        |is_cheatbroker,
        |rsa(register_ip),
        |md5(register_ip),
        |mini_openId,
        |org_id,
        |org_name,
        |rsa(plaintext_pwd),
        |md5(plaintext_pwd),
        |org_black_list_flag,
        |disabled_by,
        |union_id,
        |pwd_update_time,
        |gs_country,
        |gs_province,
        |gs_city,
        |gs_area,
        |rsa(gs_address),
        |md5(gs_address),
        |jpush_id,
        |lbs_city_code,
        |site_city_code,
        |sync_time,
        |update_time,
        |user_group_type,
        |mysql_dbname
        |from hdb.ods_hdb_mysql_broker_old
        |""".stripMargin)

  }

}
